services:
  postgres1:
    container_name: "postgres1"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres1'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - ./schema2.sql:/docker-entrypoint-initdb.d/init.sql
  postgres2:
    container_name: "postgres2"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres2'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'
    volumes:
      - ./schema2.sql:/docker-entrypoint-initdb.d/init.sql
